services:
  web:
    build: .
    image: sso-cpanel-web:latest
    restart: on-failure
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - OCTANE_SERVER=${OCTANE_SERVER}
      - OCTANE_SERVER=frankenphp
      - WITH_SCHEDULER=true
    volumes:
      - "backend_storage:/var/www/html/storage"
    ports:
      - "8000:8000"

  web-cli:
    image: sso-cpanel-web
    build: .
    restart: on-failure
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - OCTANE_SERVER=${OCTANE_SERVER}
      - OCTANE_SERVER=frankenphp
      - WITH_SCHEDULER=true
    volumes:
      - "backend_storage:/var/www/html/storage"
    entrypoint: "/bin/sh"
    tty: true


  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  backend_storage:

